### ISSUE TITLE
Meaning of exit code output from ifsck

### ISSUE THREAD

**Issue by kript** [irods/irods_client_icommands#13]
Hi Foks,

I noticed that when this command runs and completes successfully, it gives an exit code that is greater than 1 and I was wondering what the significance was.

```
$ ifsck -K -r /irods-seq-i23-bc/
$ echo $?
192
```

**Comment by kellerb** [comment]
`ifsck` will return a non-zero error code and not print anything if e.g. `verifyChksumLocFile()` has a return status that is not `USER_CHKSUM_MISMATCH`.

We can add more logging to `ifsck` for 4.1.11 to help diagnose this. Created an issue in main irods repository because icommands haven't been moved out in 4.1.11. https://github.com/irods/irods/issues/3501
